### ISSUE TITLE
swiftConventions DSL method

### ISSUE THREAD

**Issue by advayDev1** [j2objc-contrib/j2objc-gradle#144] opened 2015-06-11 21:07 UTC
By default j2objc is configured for normal objective-c, we should have a swiftConventions method in J2objcPluginExtension that sets up things like static accessor methods and bridging headers.

@confile, re #118

**Comment by brunobowden** [comment] 2015-07-02 00:15
Closing as dupe of #260

**Closed by brunobowden** 2015-07-02 00:15 UTC
Labels: duplicate, enhancement
