### ISSUE TITLE
duplicate symbols for architecture x86_64 when using --no-package-directories

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#174] opened 2015-06-14 18:03 UTC
Using a simple project just one file: 
```
package com.example;

public class SharedClass {

  public static int add(int a, int b) {
    return a+b;
  }
  
}
```
build.gradle: 
```
// The 'java' plugin must be applied before the 'j2objc' plugin
apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'com.github.j2objccontrib.j2objcgradle'


sourceCompatibility = 1.7
version = '1.0'

buildscript {
  repositories {
      maven {
          url "https://plugins.gradle.org/m2/"
      }
  }
  dependencies {
      // Current Version: https://plugins.gradle.org/plugin/com.github.j2objccontrib.j2objcgradle
//      classpath "gradle.plugin.com.github.j2objccontrib.j2objcgradle:j2objc-gradle:0.2.2-alpha"
    classpath files('/Users/mg/Downloads/j2objc-gradle/build/libs/j2objc-gradle-0.2.2-alpha.jar')
  }
}

repositories {
    mavenCentral()
    flatDir {
      dirs 'lib'
    }
}

dependencies {
}



// Plugin settings:
j2objcConfig {
    xcodeProjectDir "${projectDir}/../ios"   // Xcode workspace directory
    xcodeTarget "ios"                        // Xcode application target name
    // More: https://github.com/j2objc-contrib/j2objc-gradle/blob/master/src/main/groovy/com/github/j2objccontrib/j2objcgradle/J2objcPluginExtension.groovy#L25

    translateFlags "--no-package-directories"
}
```
Xcode compile error: 

![ios_xcworkspace](https://cloud.githubusercontent.com/assets/64265/8149764/66a33c90-12d0-11e5-9605-30c84e8503a1.png)

**Comment by advayDev1** [comment] 2015-06-14 21:18
@confile  - i cannot help much with a pod-generated file, but I see you have a -lPods-ios-j2objc-shared argument to the linked.  that is bug #128 and causes this issue as well.  we'd appreciate your help in fixing 128 - it'll fix this too =)

**Comment by advayDev1** [comment] 2015-06-14 21:18
dupe of #128

**Comment by confile** [comment] 2015-06-14 21:20
@advayDev1 I cannot fix anything until I get my project running with the new plugin.

**Closed** 2015-06-14 21:20 UTC
Labels: bug, duplicate

**Comment by advayDev1** [comment] 2015-06-14 21:27
My point is that this bug is because of the pod task.  I think you are the local expert on that, so helping in #128 is the only way to fix your issue here.
