### ISSUE TITLE
XcodeTask: Resources are included twice 

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#191] opened 2015-06-17 15:01 UTC
Resources are included twice:

![viewcontroller_swift](https://cloud.githubusercontent.com/assets/64265/8210489/86d62e84-1512-11e5-9e16-d82d253d414b.png)

**Comment by confile** [comment] 2015-06-20 17:14
That is very strange @brunobowden do you know what the difference between the yellow and the blue folders are? I suppose the once are linked and the others are copied. Can we remove the doubling here somehow?

**Comment by brunobowden** [comment] 2015-06-20 17:18
Blue is reference and will include the completer hierarchy but be ignored
for compilation. The yellow folder only includes files one level deep and
is compiled. We'll debug this after I merge in my changes. Please look in
to CocoaPods to see if there is a better way of controlling this.

**Comment by brunobowden** [comment] 2015-07-02 00:26
I'm going to look in more deeply to the Xcode integration when I get back from my trip.

**Comment by brunobowden** [comment] 2015-07-21 18:45
@confile - I see the same issue but I don't think it's high enough priority to fix. So far, it doesn't seem to cause any damage.

**Comment by confile** [comment] 2015-07-21 19:31
@brunobowden Yes you are right. We have more critical issues to fix.

**Comment by advayDev1** [comment] 2015-10-26 09:02
@brunobowden  - is this fixed?  If the final app doesn't have duplicate resources I say close as working as intended but it is just a visual reference artifact in the IDE.

**Comment by brunobowden** [comment] 2015-10-27 01:19
I'm not sure how to fix this. Closing anyway as it's just a minor visual issue rather than a big problem.

**Closed by brunobowden** 2015-10-27 01:19 UTC
Labels: cat:xcode, type:bug
