### ISSUE TITLE
Sample Gradle Project containing Android and iOS

### ISSUE THREAD

**Issue by confile** [j2objc-contrib/j2objc-gradle#161] opened 2015-06-12 15:52 UTC
It would be very helpful to have a sample project to start with satisfying this folder structure: 

```
workspace
│   .gitignore
│   build.gradle
├───android
│   │   build.gradle        // dependency on ':shared'
│   └───src                 // src/main/java/...
├───shared
│   │   build.gradle        // apply 'java' then 'j2objc' plugins
│   ├───build               // build directory
│   │   ├───...             // build output
│   │   ├───binaries        // Contains test binary: testJ2objcExecutable/debug/testJ2objc
│   │   └───j2objcOutputs   // j2objc generated headers and libraries
│   ├───lib                 // if library jar has source, then j2objc can translate it
│   └───src                 // src/main/java/... i.e. main code for translation
└───xcode
    ├───Project             // j2objcXcode configures dependency on j2objcOutputs/{libs|src}
    └───ProjectTests        // j2objcXcode configures the same except "debug" libraries
```

The sample project should:

-  help people to start very fast developing cross platform projects 
- it should include the j2objc plugin with a valid default configuration
- contain some "Hello World" output in the Android and iOS part
- should be a valid project for Android Studio
- should contain an Xcode project

I will do that but I still need some help from you @advayDev1 @brunobowden  to figure out some missing parts. Here is a structure I created so far: https://github.com/confile/Demo-Shared-iOS-Android-Project

Happy to get comments.

**Comment by brunobowden** [comment] 2015-06-12 16:21
This is great @confile. I was thinking of renaming the "xcode" folder as
"ios" since that's what most people are using it for. This'll be extremely
helpful for people.

**Comment by confile** [comment] 2015-06-12 16:28
I will create a working project and make a pull request when it is finished. Please give me feedback if you want something different.

**Comment by brunobowden** [comment] 2015-06-12 16:31
Thanks Michael

**Comment by advayDev1** [comment] 2015-06-12 18:46
@confile, this is awesome, not only will this help new folks but we could possibly use it for integration tests as well.

**Comment by confile** [comment] 2015-06-12 19:20
@brunobowden @advayDev1 How should we process here. Please guide me a bit. Should I make a pull request first and you then make comments?

**Comment by advayDev1** [comment] 2015-06-12 19:22
i'm ok with that.  don't worry about the integration testing itself, we can do that as a separate PR.

**Comment by confile** [comment] 2015-06-12 19:30
@advayDev1 Okay pull request is coming. The goal should be to create a demo project using for Xcode and for Android Studio.

**Comment by advayDev1** [comment] 2015-08-20 19:40
closing as dupe of #370

**Closed by advayDev1** 2015-08-20 19:40 UTC
Labels: status: duplicate, type: enhancement
