### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by himamis** [j2objc-contrib/j2objc-gradle#572] opened 2015-12-16 13:08 UTC
I have a huge project with over 3000 files in obscured long package names.
Because of this, TranslateTask fails, with error 'Argument list too long'.
As far as I understand this is a limitation of the Mac os of having ARG_MAX as 262144 (`getconf ARG_MAX` or `sysctl -A | grep kern.argmax`).
Is there a solution to this problem? (Maybe translating in multiple steps, or giving jar with sources as argument)

build.grade file
```groovy
buildscript {
	repositories {
		maven {
			url 'https://plugins.gradle.org/m2/'
		}
	}
	dependencies {
		classpath 'gradle.plugin.com.github.j2objccontrib.j2objcgradle:j2objc-gradle:0.5.0-alpha'
	}
}

configure([project(':common'), project(':ggbjdk')]) {
	// inject j2objc gradle plugin into common projects
	apply plugin: 'com.github.j2objccontrib.j2objcgradle'

	j2objcConfig {
		autoConfigureDeps true

		xcodeProjectDir '../ios/JavaClasses'

		finalConfigure()
	}
}

task wrapper(type: Wrapper) {
	gradleVersion = '2.8'
}
```

Nothing is printed as error, but if I take the command that is called and copy paste it into terminal, I get the `Argument list too long` error.

j2objc version 0.9.8.2.1

**Comment by brunobowden** [comment] 2015-12-16 17:49
Hi @hinamis,
Thanks for doing your research before posting this issue. The plugin will normally pass through the error but I can imagine it has difficulties in this particular case. I think there's two possible workarounds and also likely a way of doing a proper fix in the plugin. Given that I like neither of the workarounds, it would be very helpful to get a PR from you to do the fix in the plugin. If my guesses are correct, then the fix shouldn't be too difficult. I'd also appreciate you doing the fix as you'll be able to test it properly as well.

So here are the workarounds followed by the potential proper plugin fix:

1) Reduce the average filepath:
Given the 262,144 limit (I presume this is a character limit?) and 3,000 files, the obvious workaround is keep the average filepath to less than 85 characters (262,144 / 3,000 = 87). If you're root directly is `/Users/SomethingLongThatCanBeMadeSmaller`, then that's easy. Otherwise you could replace the package names throughout the whole project but that's a big pain.

2) Split in to multiple projects:
If you can split the project in to multiple Java projects, then J2ObjC and the plugin will gracefully handle the conversation... and do it in separate passes. See https://github.com/j2objc-contrib/j2objc-gradle/blob/master/dependencies.md#multiple-projects-and-external-libraries. This is again quite a pain.

3) Refactor the plugin to make this work:
The j2objc arguments should be limited in size, it's the list of source files that's a challenge. I believe that's there's two ways of fixing the plugin to make this work:

3A) Split the source files in to multiple commands:
As long as all the command line arguments are the same, I think you can quite happily split the source file list in to two or more parts and then run them sequentially. Look at the `args file.path` line in the TranslateTask method:
https://github.com/j2objc-contrib/j2objc-gradle/blob/master/src/main/groovy/com/github/j2objccontrib/j2objcgradle/tasks/TranslateTask.groovy#L342

3B) Place the source files in to a temp file:
The `j2objc` command tries to be as close as possible to the `javac` command line - so firstly I wonder how you compiled this with `javac` without encountering the same problem? Since the same problem does occur with a Java only build, Oracle published a workaround where you write the list of source files to a temporary file and compile that, see here:
http://docs.oracle.com/javase/6/docs/technotes/tools/windows/javac.html#commandlineargfile

For both 3A and 3B, that would be the preferred long term fix. I would try experimenting with both using the copied and pasted command line, to see if that works. Assuming both works, I'd prefer the temporary file as OS agnostic and will also work with CycleFinder, which I presume needs all the source files in one go and can't be split. Though good luck trying with CycleFinder on a large project like that!

Here's the guide on working with the plugin. You'll find us super responsive on code reviews and the code is already in good shape and well tested:
https://github.com/j2objc-contrib/j2objc-gradle/blob/master/CONTRIBUTING.md#quick-start



Btw, there's a simpler (and shorter) way of loading the plugin... but it may not work with the multiple apply that you're doing.
```
plugins {
    id 'java'
    id 'com.github.j2objccontrib.j2objcgradle' version '0.5.0-alpha'
}
```

**Comment by brunobowden** [comment] 2015-12-16 18:10
@himamis - I just tested the temp file and it worked in a simple test. I'd go ahead with 3B. If the command is longer than MAX_ARG - 2048 (add comment mentioning leaving space for the environment and referring to http://www.in-ulm.de/~mascheck/various/argmax/). Then put all the source files in a temp file, placed in [temporaryDir()](https://docs.gradle.org/current/dsl/org.gradle.api.Task.html#org.gradle.api.Task:temporaryDir) and pass that to the command line using the `@j2objc-args-filepaths` syntax.

@tomball - this is for working around having too many source files and getting the error "Argument list too long". The Oracle suggested workaround is to use a temporary file that lists all the source files - I've confirmed that `j2objc` supports this. Would you suggest anything different?

@advayDev1 - let me know if you have any different thoughts on this.

**Comment by himamis** [comment] 2015-12-17 08:04
Dear @brunobowden,

Thank you for your lengthy and detailed answer! I am willing to do the long term fix and issue a PR. Unfortunately I cannot do this in this year, I won't be available until 11th of January.

**Comment by brunobowden** [comment] 2015-12-17 08:34
Not a problem for us ;-)

Though I hope we'll see more of you come January.

**Comment by brunobowden** [comment] 2016-01-06 21:40
@himamis - just a note for the future, if you put `fixes #572` in the PR, then it will automatically close the associated issue when the PR is merged. In this case, you put `fixes issue #572` which GitHub doesn't recognize. Minor issue but nice trick to know for the future:

https://help.github.com/articles/closing-issues-via-commit-messages/

I'll respin the client version later today.

**Closed by brunobowden** 2016-01-06 21:40 UTC

**Comment by brunobowden** [comment] 2016-01-07 16:15
@himamis - Can comment on this PR confirming your acceptance of our Contributor License Agreement. Thanks:

I, <full name> (<email@example.com>, https://github.com/<github username>), certify that
a) this Contribution is my original work, and
b) I have the right to submit this Contribution under the Apache License,
   Version 2.0 (the "License") available at
   http://www.apache.org/licenses/LICENSE-2.0, and
c) I am submitting this Contribution under the License.

**Comment by himamis** [comment] 2016-01-08 08:51
I, Balázs Bencze (megette_a@yahoo.com, https://github.com/himamis), certify that
a) this Contribution is my original work, and
b) I have the right to submit this Contribution under the Apache License,
Version 2.0 (the "License") available at
http://www.apache.org/licenses/LICENSE-2.0, and
c) I am submitting this Contribution under the License.

**Comment by brunobowden** [comment] 2016-01-08 15:02
Thanks
